import { chromium } from "playwright";
const b = await chromium.launch();
const p = await (await b.newContext({ viewport:{width:1440,height:760}, deviceScaleFactor:2 })).newPage();
await p.goto("http://localhost:3000", { waitUntil:"networkidle", timeout:30000 });
await p.waitForTimeout(2000);
await p.evaluate(() => window.scrollTo(0, 720));
await p.waitForTimeout(800);
await p.screenshot({ path: "C:/Users/eobi6/zerocup/frontend/.shots/strip.png" });
console.log("ok");
await b.close();
