/** Typed ABI for the deployed GafferArena (v2) contract — the parts the app uses.
 *  Agents are ERC-721 NFTs (identified by agentId); contests reference agents by id. */
export const managerAiAbi = [
  { type: "function", name: "nextContestId", stateMutability: "view", inputs: [], outputs: [{ type: "uint256" }] },
  { type: "function", name: "nextAgentId", stateMutability: "view", inputs: [], outputs: [{ type: "uint256" }] },
  {
    type: "function", name: "getContest", stateMutability: "view",
    inputs: [{ name: "contestId", type: "uint256" }],
    outputs: [
      { name: "id", type: "uint256" },
      { name: "name", type: "string" },
      { name: "prizePool", type: "uint256" },
      { name: "entryFee", type: "uint256" },
      { name: "startTime", type: "uint256" },
      { name: "endTime", type: "uint256" },
      { name: "resolved", type: "bool" },
      { name: "participantCount", type: "uint256" },
      { name: "creator", type: "address" },
      { name: "isPrivate", type: "bool" },
      { name: "brief", type: "string" },
    ],
  },
  { type: "function", name: "getParticipants", stateMutability: "view", inputs: [{ name: "contestId", type: "uint256" }], outputs: [{ type: "uint256[]" }] },
  {
    type: "function", name: "getAgent", stateMutability: "view",
    inputs: [{ name: "agentId", type: "uint256" }],
    outputs: [
      { name: "owner", type: "address" },
      { name: "configHash", type: "string" },
      { name: "contestsEntered", type: "uint256" },
      { name: "roundsScored", type: "uint256" },
      { name: "totalPoints", type: "uint256" },
      { name: "totalEffective", type: "uint256" },
      { name: "wins", type: "uint256" },
      { name: "overrideCount", type: "uint256" },
      { name: "tier", type: "uint256" },
      { name: "eligible", type: "bool" },
      { name: "minted", type: "bool" },
      { name: "price", type: "uint256" },
    ],
  },
  {
    type: "function", name: "getEntry", stateMutability: "view",
    inputs: [{ name: "contestId", type: "uint256" }, { name: "agentId", type: "uint256" }],
    outputs: [
      { name: "active", type: "bool" },
      { name: "totalPoints", type: "uint256" },
      { name: "overrideCount", type: "uint256" },
      { name: "multiplier", type: "uint256" },
      { name: "effectiveScore", type: "uint256" },
      { name: "entryTime", type: "uint256" },
    ],
  },
  { type: "function", name: "ownerOf", stateMutability: "view", inputs: [{ type: "uint256" }], outputs: [{ type: "address" }] },
  { type: "function", name: "balanceOf", stateMutability: "view", inputs: [{ type: "address" }], outputs: [{ type: "uint256" }] },
  { type: "function", name: "listingPrice", stateMutability: "view", inputs: [{ type: "uint256" }], outputs: [{ type: "uint256" }] },
  { type: "function", name: "isEligible", stateMutability: "view", inputs: [{ type: "uint256" }], outputs: [{ type: "bool" }] },
  { type: "function", name: "agentOwner", stateMutability: "view", inputs: [{ type: "uint256" }], outputs: [{ type: "address" }] },
  { type: "function", name: "level", stateMutability: "view", inputs: [{ type: "uint256" }], outputs: [{ type: "uint256" }] },
  { type: "function", name: "pendingWithdrawals", stateMutability: "view", inputs: [{ type: "address" }], outputs: [{ type: "uint256" }] },

  { type: "function", name: "createAgent", stateMutability: "nonpayable", inputs: [{ name: "configHash", type: "string" }], outputs: [{ type: "uint256" }] },
  { type: "function", name: "mintAgent", stateMutability: "nonpayable", inputs: [{ name: "agentId", type: "uint256" }], outputs: [] },
  { type: "function", name: "updateAgentConfig", stateMutability: "nonpayable", inputs: [{ name: "agentId", type: "uint256" }, { name: "configHash", type: "string" }], outputs: [] },
  {
    type: "function", name: "createContest", stateMutability: "nonpayable",
    inputs: [
      { name: "name", type: "string" },
      { name: "entryFee", type: "uint256" },
      { name: "startTime", type: "uint256" },
      { name: "endTime", type: "uint256" },
      { name: "isPrivate", type: "bool" },
      { name: "brief", type: "string" },
    ],
    outputs: [{ type: "uint256" }],
  },
  { type: "function", name: "enterContest", stateMutability: "payable", inputs: [{ name: "contestId", type: "uint256" }, { name: "agentId", type: "uint256" }], outputs: [] },
  { type: "function", name: "listAgent", stateMutability: "nonpayable", inputs: [{ name: "agentId", type: "uint256" }, { name: "price", type: "uint256" }], outputs: [] },
  { type: "function", name: "unlistAgent", stateMutability: "nonpayable", inputs: [{ name: "agentId", type: "uint256" }], outputs: [] },
  { type: "function", name: "buyAgent", stateMutability: "payable", inputs: [{ name: "agentId", type: "uint256" }], outputs: [] },
  { type: "function", name: "claim", stateMutability: "nonpayable", inputs: [], outputs: [] },

  {
    type: "event", name: "AgentCreated",
    inputs: [
      { name: "agentId", type: "uint256", indexed: true },
      { name: "owner", type: "address", indexed: true },
      { name: "configHash", type: "string", indexed: false },
    ],
  },
  {
    type: "event", name: "AgentMinted",
    inputs: [
      { name: "agentId", type: "uint256", indexed: true },
      { name: "owner", type: "address", indexed: true },
    ],
  },
  {
    type: "event", name: "ContestCreated",
    inputs: [
      { name: "contestId", type: "uint256", indexed: true },
      { name: "creator", type: "address", indexed: true },
      { name: "name", type: "string", indexed: false },
      { name: "entryFee", type: "uint256", indexed: false },
      { name: "isPrivate", type: "bool", indexed: false },
      { name: "startTime", type: "uint256", indexed: false },
      { name: "endTime", type: "uint256", indexed: false },
    ],
  },
  {
    type: "event", name: "AgentEntered",
    inputs: [
      { name: "contestId", type: "uint256", indexed: true },
      { name: "agentId", type: "uint256", indexed: true },
      { name: "owner", type: "address", indexed: true },
      { name: "entryFee", type: "uint256", indexed: false },
    ],
  },
  {
    type: "event", name: "PointsRecorded",
    inputs: [
      { name: "contestId", type: "uint256", indexed: true },
      { name: "agentId", type: "uint256", indexed: true },
      { name: "matchId", type: "uint256", indexed: true },
      { name: "points", type: "uint256", indexed: false },
      { name: "decisionHash", type: "string", indexed: false },
    ],
  },
  {
    type: "event", name: "AgentSold",
    inputs: [
      { name: "agentId", type: "uint256", indexed: true },
      { name: "from", type: "address", indexed: true },
      { name: "to", type: "address", indexed: true },
      { name: "price", type: "uint256", indexed: false },
    ],
  },
] as const;
